name: TestPlugin
version: 0.0.1.${build.number}
description: Testing and demonstration plugin using SpoutAPI.
authors: [SpoutDev, Afforess, Wulfspider, alta189, Raphfrk, narrowtux, Top_Cat]
website: http://www.getspout.org

main: org.getspout.testplugin.TestPlugin

depend: [Spout]
