name: SpoutTest
version: 0.0.1.${build.number}
description: Testing and demonstration suite for Spout.
authors: [SpoutDev, Afforess, Wulfspider, alta189, Raphfrk, narrowtux, Top_Cat]
website: http://www.getspout.org

main: org.getspout.spouttest.SpoutTest
depend: [Spout]
